name: Pylint

on: [push]

jobs:
  python-black:
    runs-on: ubuntu-latest
    if: |
      ${{ !contains(github.event.head_commit.message, 'Apply Code Formatter Change') }}
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}
      - name: Install Poetry
        run: |
          pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install --with dev --no-interaction
      - name: black
        run: poetry run black .
      - name: Auto Commit
        if: github.event_name == 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Code Formatter Change
